language: node_js
node_js:
  - "4.2.6"
cache:
  directories:
    - node_modules
sudo: required
before_install:
  - npm install node -g node-gyp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run coveralls
