language: node_js
node_js:
  - "4.2.6"
cache:
  directories:
    - node_modules
addons:
  - rethinkdb: '2.3.5'
install:
  - npm install
before_script:
  - npm run lint
  - rethinkdb
script:
  - npm run coveralls
